### ISSUE TITLE
A problem regarding calculating phylogenetic signal (λ) via R

### ISSUE THREAD

**Issue by PyrrhaNiko** [emmanuelparadis/ape#18]
Hey guys,

I hope this message finds you well!

We collected data (Percentage correct of chosen tests, percentage correct of forced tests, and memory tests declined) of 6 primates---rhesus monkey, Japanese macaque, gorilla, chimpanzee, capuchin monkey, and orangutan. Currently, we are planning to calculate phylogenetic signal (λ) via R with several R packages, including ape, phytools, and geiger. We plotted a phylogenetic tree via an online tool called phyloT. However, when we import our tree to R, we were told that the tree has no branch lengths. This is our first problem. To handle this probelm, we tried to draw our phylogenetic tree through r package ape and we ended up with a tree that has branch lengths (see it in attachments). But when we tried to calculate λ again, we were told by R that "Error in solve.default(Cl) : LAPACK routine dgesv: the system is exactly singular: u [1,1] = 0". Now, we are stuck in this second problem. 

Would you please give some suggestions for these problems? Please let me know if there's any confusion in my description. 

So many thanks in advance!

Sincerely,

Ethan

**Comment by emmanuelparadis** [comment]
Hi Ethan,
A tree in Newick format may have, or not, branch lengths. In both cases, you can read it with ape. Without branch lengths, you cannot estimate phylogenetic signal with models such as Brownian motion, Pagel's, etc. There are several phylogenies of Primates published with branch lengths, so you can resolve your problem relatively easily.
I think your message is more appropriate to a forum like r-sig-phylo since this is hardly an issue with ape (or phytools as well).
Best,
Emmanuel
