### ISSUE TITLE
Ladderize results C stack usage overflow

### ISSUE THREAD

**Issue by teng-gao** [emmanuelparadis/ape#54]
Hi Emmanuel, 

We found that for certain tree structures, `ladderize` function results in C stack overflow. For example,

[tree.rds.zip](https://github.com/emmanuelparadis/ape/files/8547525/tree.rds.zip)

```
> tree = readRDS('tree.rds')
> ape::ladderize(tree)
Error: C stack usage  7971204 is too close to the limit
```

This seems to result from the recursive `foo` function to reorder edges. Do you think there is an easy fix to this? Would really appreciate your help.

Thanks,
Teng

**Comment by evanbiederstedt** [comment]
I could make a pull request to fix this behavior, if I could only get an example whereby the C stack overflow bug happens. 

The function is here: https://github.com/emmanuelparadis/ape/blob/master/R/ladderize.R#L12-L27

We could fix this pretty quickly with a [trampoline](https://en.wikipedia.org/wiki/Trampoline_(computing)#:~:text=Trampolines%20(sometimes%20referred%20to%20as,bounces%2C%20hence%20the%20term%20trampoline.), using this package: https://github.com/rdinnager/trampoline

**Comment by emmanuelparadis** [comment]
Hi @teng-gao,
I plotted your tree with the option `show.tip.label = FALSE` and it took me a few seconds to make sense of the plot! Your tree is (almost) totally unbalanced so that `ladderize()` has to call the recursive internal function all along it. Similarly (and unsurprisingly), `balance(tree)` gives the same error. I tried to fix different parameters inside or outside R but this didn't help. See [here](https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit) for a discussion on stacks in R with some useful info.
This could be related to issue #53: maybe Lenore's tree is much more imbalanced than a random tree (`write.tree` calls some recursive functions as well).
I don't see a simple solution right now, except rewriting the code avoiding recursive calls as suggested by @evanbiederstedt.
Emmanuel

**Comment by KlausVigo** [comment]
Hi all, 
there is a fix in the pull request I just made. 

PS: @teng-gao the tree you send contains ~2x too many `edge.length`'s.

**Comment by teng-gao** [comment]
Just tested the iterative version by @KlausVigo and it works on my case!

**Comment by evanbiederstedt** [comment]
Thanks @KlausVigo 

I commented on the PR. Works for me as well---I wouldn't have been able to so quickly solve this. 

There's a warning but that's probably ok.

Thanks, Evan

**Comment by emmanuelparadis** [comment]
Excellent! I've merged Klaus's PR. I'm now working on removing the recursive call from `write.tree()`.
