### ISSUE TITLE
read.nexus.data does not handle continuous characters

### ISSUE THREAD

**Issue by brpetrucci** [emmanuelparadis/ape#6]
Hello. I've been using write.nexus.data and read.nexus.data for storing and reading continuous data for my trait-dependent simulations, and realized some time ago that read.nexus.data does not work with continuous character. From looking at the source code, that seems to come from the `strpsplit` of `Seq` on lines 157 and 170. I used `fix()` to solve it on my local use, but figured I could point out the issue here. If the function is not intended to be used with continuous characters that is fair, but it might be good to include that in the documentation

**Comment by emmanuelparadis** [comment]
Hi. These two functions have been written and patched by various persons, so they lack some consistency in the code and the documentation. It seems that the restriction you mention is written as a comment in the code.

If you want to contribute a fix/patch, then you'd be very welcome. Otherwise I can add a line in the help page.

**Comment by brpetrucci** [comment]
I will be able to contribute a fix/patch soon, but until June I'm too busy. For the moment a line on the help page should suffice!
